[package]
name = "ruggle"
version = "0.1.0"
authors = ["Tung Nguyen <tungtn3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "0.52.0"
pistoncore-sdl2_window = "0.66.0"
piston2d-graphics = "0.37.0"
piston2d-opengl_graphics = "0.74.0"
image = "0.23.11"
rusttype = "0.9.2"
bitflags = "1.0"

[patch.crates-io]
pistoncore-sdl2_window = { path = "../sdl2_window" }
